export interface ResearchPaper {
  title: string;
  authors: string;
  authorRole: string | null;
  facultySlug: string | null;
  area: string;
  date: string | null;
  publicationYear: number | null;
  link: string | null;
  linkLabel: string | null;
  publisher: string | null;
  indexing: string | null;
  quartile: string | null;
  metrics: string | null;
  authorPosition: string | null;
}

// Publications by Faculty of Business / Department of Business
// Administration staff. Source: the Research & Publications table in
// .vscode/facultyinfo — regenerate from the DB if that document changes.
export const researchPapers: ResearchPaper[] = [
  {
    title: 'Molla, M. A. A.. (2025). The role of leadership styles in enhancing academic and administrative efficiency in Bangladeshi private universities. International Journal of Business and Management (IJBM).',
    authors: 'Prof. Md. Al-Amin Molla',
    authorRole: 'Professor & Dean',
    facultySlug: 'al-amin-mollah',
    area: 'International Emerging Scholars Society (IESS), New Zealand · Non-Indexed',
    date: '2025',
    publicationYear: 2025,
    link: 'https://doi.org/10.56879/ijbm.v4i2.141',
    linkLabel: null,
    publisher: 'International Emerging Scholars Society (IESS), New Zealand',
    indexing: 'Non-Indexed',
    quartile: null,
    metrics: null,
    authorPosition: '1st',
  },
  {
    title: 'Molla, M. A. A.. (2025). Evaluating the Quality of Higher Education in Private Universities of Bangladesh: Challenge, Developments, and the Path Forward. Sonargaon University Journal.',
    authors: 'Prof. Md. Al-Amin Molla',
    authorRole: 'Professor & Dean',
    facultySlug: 'al-amin-mollah',
    area: 'Sonargaon University (SU), BD · Non-Indexed',
    date: '2025',
    publicationYear: 2025,
    link: null,
    linkLabel: null,
    publisher: 'Sonargaon University (SU), BD',
    indexing: 'Non-Indexed',
    quartile: null,
    metrics: null,
    authorPosition: '1st',
  },
  {
    title: 'Islam, M.S., Effect of Green Investment, Renewable Energy Consumption, and Carbon Tax Policies on Ecological Sustainability: Evidence from ASEAN Countries, Journal of Economics, Management & Business Administration',
    authors: 'Dr. Md. Shoriful Islam',
    authorRole: 'Associate Professor & Head',
    facultySlug: 'shoriful-islam',
    area: 'AIRSD · International Non-indexed',
    date: '2026',
    publicationYear: 2026,
    link: 'https://doi.org/10.59075/jemba.v5i1.639',
    linkLabel: null,
    publisher: 'AIRSD',
    indexing: 'International Non-indexed',
    quartile: null,
    metrics: null,
    authorPosition: 'Sole author',
  },
  {
    title: 'Ayoungman, F.Z., Islam, M. S. (Corresponding author), Chishti, M.Z., & Zhang, F.L., Toward Achieving Sustainable Development Goal 13 in Developing Countries: Microcredit to Environmental Degradation, Journal: Sustainable Development,',
    authors: 'Dr. Md. Shoriful Islam',
    authorRole: 'Associate Professor & Head',
    facultySlug: 'shoriful-islam',
    area: 'Wiley · SCOPUS & WoS SSCI · Q1 · CiteScore: 14.5 IF: 8.2',
    date: '2026',
    publicationYear: 2026,
    link: 'https://doi.org/10.1002/sd.70888',
    linkLabel: null,
    publisher: 'Wiley',
    indexing: 'SCOPUS & WoS SSCI',
    quartile: 'Q1',
    metrics: 'CiteScore: 14.5 IF: 8.2',
    authorPosition: '2nd & corresponding',
  },
  {
    title: 'Ayoungman, F.Z., Islam, M. S. (Corresponding author), Chishti, M.Z., & Shawon, A.H., (2025), A pathway towards sustainable development: Analysing the influential role of microfinancing on environmental quality in developing nations. Journal: Sustainable Development,',
    authors: 'Dr. Md. Shoriful Islam',
    authorRole: 'Associate Professor & Head',
    facultySlug: 'shoriful-islam',
    area: 'Wiley · SCOPUS & WoS- SSCI · Q1 · CiteScore: 14.5 IF: 8.2',
    date: '2025',
    publicationYear: 2025,
    link: 'https://doi.org/10.1002/sd.70188',
    linkLabel: null,
    publisher: 'Wiley',
    indexing: 'SCOPUS & WoS- SSCI',
    quartile: 'Q1',
    metrics: 'CiteScore: 14.5 IF: 8.2',
    authorPosition: '2nd & corresponding',
  },
  {
    title: 'Ayoungman, F.Z., Islam, M.S. (Corresponding author), Zhang, F.L., & Shawon, A.H., (2025), Social Enterprise\'s Initiatives for Socioeconomic Sustainability: Appraisal based on Morphogenetic/Morphostatic Approach and Opportunity Co-creation theory. Journal of Knowledge Economy, , ,',
    authors: 'Dr. Md. Shoriful Islam',
    authorRole: 'Associate Professor & Head',
    facultySlug: 'shoriful-islam',
    area: 'Springer Nature · ABS 1 & SCOPUS · Q1 · IF: 5.19',
    date: '2025',
    publicationYear: 2025,
    link: 'https://doi.org/10.1007/s13132-025-02766-x',
    linkLabel: null,
    publisher: 'Springer Nature',
    indexing: 'ABS 1 & SCOPUS',
    quartile: 'Q1',
    metrics: 'IF: 5.19',
    authorPosition: '2nd & corresponding',
  },
  {
    title: 'Ayoungman, F.Z., Islam, M.S. (Corresponding author), Masukujjaman, M., Shawon, A.H., & Mahmud, A.A., (2025), Financial Factors Influencing Investment Willingness in Environment-Friendly Business: Empirical Study on an Emerging Economy, Innovation and Green Development,',
    authors: 'Dr. Md. Shoriful Islam',
    authorRole: 'Associate Professor & Head',
    facultySlug: 'shoriful-islam',
    area: 'Elsevier · SCOPUS · Q1 · IF: 18.6',
    date: '2025',
    publicationYear: 2025,
    link: 'https://doi.org/10.1016/j.igd.2025.100206',
    linkLabel: null,
    publisher: 'Elsevier',
    indexing: 'SCOPUS',
    quartile: 'Q1',
    metrics: 'IF: 18.6',
    authorPosition: '2nd & corresponding',
  },
  {
    title: 'Islam, M.S., (2025), Nongovernmental Organizations Transforming into Social Enterprises in the Process of Institutionalizing Solutions to Major Social Crises for Ensuring Sustainable Social Development. Zakaria Journal of Social Science,',
    authors: 'Dr. Md. Shoriful Islam',
    authorRole: 'Associate Professor & Head',
    facultySlug: 'shoriful-islam',
    area: 'International Non-indexed',
    date: '2025',
    publicationYear: 2025,
    link: 'https://doi.org/10.59075/zjss.v4i1.518',
    linkLabel: null,
    publisher: null,
    indexing: 'International Non-indexed',
    quartile: null,
    metrics: null,
    authorPosition: 'Sole author',
  },
  {
    title: 'Zhang, F.L., Ayoungman, F.Z., & Islam, M.S., (2023), Institutional Capital, Ancestral Hall, and the Reshaping of Ancient Rule: an Empirical Analysis of the New Energy of Chinese Heritage Elements in Rural Revitalization, Journal of Knowledge Economy, Springer Nature, ABS 1, JCR Q1, Pages 2726–2760,',
    authors: 'Dr. Md. Shoriful Islam',
    authorRole: 'Associate Professor & Head',
    facultySlug: 'shoriful-islam',
    area: 'Springer Nature · ABS 1 · Q1 · IF: 5.19',
    date: '2023',
    publicationYear: 2023,
    link: 'https://doi.org/10.1007/s13132-023-01243-7',
    linkLabel: null,
    publisher: 'Springer Nature',
    indexing: 'ABS 1',
    quartile: 'Q1',
    metrics: 'IF: 5.19',
    authorPosition: '3rd author',
  },
  {
    title: 'Ayoungman, F.Z., Shawon, A.H., Ahmed, R.R., Khan, M.K., Islam, M.S., (2023), Exploring the economic impact of institutional entrepreneurship, social Innovation, and poverty reduction on carbon footprint in BRICS countries: what is the role of social enterprise?, Environmental Science & Pollution Research (ESPR), Springer Nature, SCIE, Scopus, Impact Score: 6.18, JCR Q1,',
    authors: 'Dr. Md. Shoriful Islam',
    authorRole: 'Associate Professor & Head',
    facultySlug: 'shoriful-islam',
    area: 'Springer Nature · WoS- SCIE, SCOPUS · Q2 · CiteScore: 12.1 IF: 5.59',
    date: '2023',
    publicationYear: 2023,
    link: 'http://dx.doi.org/10.1007/s11356-023-30868-z',
    linkLabel: null,
    publisher: 'Springer Nature',
    indexing: 'WoS- SCIE, SCOPUS',
    quartile: 'Q2',
    metrics: 'CiteScore: 12.1 IF: 5.59',
    authorPosition: '5th author',
  },
  {
    title: 'Zhang, F.L., Islam, M.S., Ayoungman, F.Z., Wang, Y., (2023), Butterfly Change of Commercial Enterprise into Social Enterprise: Based on Mechanism and Case Study of Institutional Capital, Journal of Social Entrepreneurship,',
    authors: 'Dr. Md. Shoriful Islam',
    authorRole: 'Associate Professor & Head',
    facultySlug: 'shoriful-islam',
    area: 'Taylor & Francis · Scopus, ESCI, EBSCO · Q1 · CiteScore: 8.1 IF: 3.6',
    date: '2023',
    publicationYear: 2023,
    link: 'https://doi.org/10.1080/19420676.2023.2193604',
    linkLabel: null,
    publisher: 'Taylor & Francis',
    indexing: 'Scopus, ESCI, EBSCO',
    quartile: 'Q1',
    metrics: 'CiteScore: 8.1 IF: 3.6',
    authorPosition: '2nd author',
  },
  {
    title: 'Ayoungman, F.Z., Shawon, A.H., Islam, M.S., Kalam, A., (2023), A STUDY ON THE EFFECTIVENESS OF SUSTAINABLE STRUCTURE OF EMERGING SOCIAL ENTERPRISES TO ERADICATE IMPOVERISHMENT: THE REHABILITATION PARADIGM IN BANGLADESH, Russian Law Journal,',
    authors: 'Dr. Md. Shoriful Islam',
    authorRole: 'Associate Professor & Head',
    facultySlug: 'shoriful-islam',
    area: 'ESCI, SCOPUS · Q3 · Cite score: 0.48',
    date: '2023',
    publicationYear: 2023,
    link: 'https://doi.org/10.52783/rlj.v11i4s.868',
    linkLabel: null,
    publisher: null,
    indexing: 'ESCI, SCOPUS',
    quartile: 'Q3',
    metrics: 'Cite score: 0.48',
    authorPosition: '3rd author',
  },
  {
    title: 'Sikder, S. ., Rana , M. M. ., & Polas, M. R. H. (2022). Service Quality Dimensions (SERVQUAL) and Customer Satisfaction towards Motor Ride-Sharing Services: Evidence from Bangladesh. Annals of Management and Organization Research, 3(2), 97–113.',
    authors: 'Sharmila Sikder',
    authorRole: 'Assistant Professor',
    facultySlug: 'sharmila-sikder',
    area: 'Goodwood Publishing',
    date: '2022',
    publicationYear: 2022,
    link: 'https://doi.org/10.35912/amor.v3i2.1184',
    linkLabel: null,
    publisher: 'Goodwood Publishing',
    indexing: null,
    quartile: null,
    metrics: null,
    authorPosition: '1st',
  },
  {
    title: 'M. R. H. Polas et al., "Toward a Greener Horizon: Unraveling the Links Among Environmental Awareness, Consumption Values, and Packaging in Consumer Decision Making," in IEEE Engineering Management Review, vol. 53, no. 4, pp. 99-120, Aug. 2025, doi: 10.1109/EMR.2024.3438124.',
    authors: 'Sharmila Sikder',
    authorRole: 'Assistant Professor',
    facultySlug: 'sharmila-sikder',
    area: 'IEEE Engineering Management Review · SCOPUS · Q1 · Cite Score: 4.9 IF: 5.3',
    date: '2025',
    publicationYear: 2025,
    link: null,
    linkLabel: null,
    publisher: 'IEEE Engineering Management Review',
    indexing: 'SCOPUS',
    quartile: 'Q1',
    metrics: 'Cite Score: 4.9 IF: 5.3',
    authorPosition: '5th',
  },
  {
    title: 'Hawlader, M. R., Rana, M. M., Kalam, A., & Polas, M. R. H. (2021). Consideration of workers’ opinion in the decision making process in the RMG Sector: Evidence from Bangladesh. Journal of Sustainable Tourism and Entrepreneurship, 2(4), 267 282.',
    authors: 'Md. Rasel Hawlader',
    authorRole: 'Assistant Professor & Course Coordinator',
    facultySlug: 'rasel-hawlader',
    area: 'Goodwood Publishing',
    date: '2021',
    publicationYear: 2021,
    link: 'https://doi.org/10.35912/joste.v2i4.983',
    linkLabel: null,
    publisher: 'Goodwood Publishing',
    indexing: null,
    quartile: null,
    metrics: null,
    authorPosition: '1st',
  },
  {
    title: 'Hawlader, M. R., Rana, M. M., Kalam, A., & Polas, M. R. H. (2022). Empowering workers’ involvement: Unveiling the dynamics of communication, recognition, productivity, and decision-making in the RMG sector. Journal of Sustainable Tourism and Entrepreneurship, 3(3), 195-215.',
    authors: 'Md. Rasel Hawlader',
    authorRole: 'Assistant Professor & Course Coordinator',
    facultySlug: 'rasel-hawlader',
    area: 'Goodwood Publishing',
    date: '2022',
    publicationYear: 2022,
    link: 'https://doi.org/10.35912/joste.v3i3.1511',
    linkLabel: null,
    publisher: 'Goodwood Publishing',
    indexing: null,
    quartile: null,
    metrics: null,
    authorPosition: '1st',
  },
  {
    title: 'Islam M. I., & Hawlader, M. R. (2024). Corporate Governance Practices in Bangladesh: An Overview of Pharmaceutical, Chemical and Ceramic Industry. Sonargaon University Journal, Volume 4 Issue I & II.',
    authors: 'Md. Rasel Hawlader',
    authorRole: 'Assistant Professor & Course Coordinator',
    facultySlug: 'rasel-hawlader',
    area: 'Sonargaon University',
    date: '2024',
    publicationYear: 2024,
    link: 'https://su.edu.bd/web_assets/journal/journal_four/06%20Md.%20Imranul%20Islam.pdf',
    linkLabel: null,
    publisher: 'Sonargaon University',
    indexing: null,
    quartile: null,
    metrics: null,
    authorPosition: '2nd',
  },
  {
    title: 'Chowdhury F.Y., & Hawlader, M. R. (2024). Sustainable Growth Strategies for Bangladesh’s Leather Industry: Policy Recommendations and Future Perspectives. International Journal of Business and Management; Vol. 19, No. 2; 2024. ISSN 1833-3850 E-ISSN 1833-8119. DOI:10.5539/ijbm. v19n2p120',
    authors: 'Md. Rasel Hawlader',
    authorRole: 'Assistant Professor & Course Coordinator',
    facultySlug: 'rasel-hawlader',
    area: 'Canadian Center of Science and Education',
    date: '2024',
    publicationYear: 2024,
    link: null,
    linkLabel: null,
    publisher: 'Canadian Center of Science and Education',
    indexing: null,
    quartile: null,
    metrics: null,
    authorPosition: '2nd',
  },
  {
    title: 'Alam, M. S., Hawlader, M. R., & Chowdhury, F. Y. (2024). Job Satisfaction of Bankers in Islami Shariah-based Private Commercial Banks of Bangladesh: Application of Job Characteristics Model. International Journal of Business, Management and Economics, 5(3), 220-235.',
    authors: 'Md. Rasel Hawlader',
    authorRole: 'Assistant Professor & Course Coordinator',
    facultySlug: 'rasel-hawlader',
    area: 'Training & Research Institute Jeramba Ilmu Sukses',
    date: '2024',
    publicationYear: 2024,
    link: 'https://doi.org/10.47747/ijbme.v5i3.1826',
    linkLabel: null,
    publisher: 'Training & Research Institute Jeramba Ilmu Sukses',
    indexing: null,
    quartile: null,
    metrics: null,
    authorPosition: '2nd',
  },
  {
    title: 'Das, A., Alam, M. S., & Hawlader, M. R. (2025). Unveiling the impact of green innovation on organizational performance: An empirical study on FMCG sector in Bangladesh. Annals of Management and Organization Research, 7(2), 247-267.',
    authors: 'Md. Rasel Hawlader',
    authorRole: 'Assistant Professor & Course Coordinator',
    facultySlug: 'rasel-hawlader',
    area: 'Goodwood Publishing',
    date: '2025',
    publicationYear: 2025,
    link: 'https://doi.org/10.35912/amor.v7i2.3241',
    linkLabel: null,
    publisher: 'Goodwood Publishing',
    indexing: null,
    quartile: null,
    metrics: null,
    authorPosition: '3rd',
  },
  {
    title: 'Hawlader, M. R., Polas, M. R. H., Das, A., Alam, M. S., Uddin, S. M., Hasan, T., & Pantho, O. G. (2026). Green human resource management and green innovation as drivers of environmental performance in readymade garment firms. Discover Sustainability (2026).',
    authors: 'Md. Rasel Hawlader',
    authorRole: 'Assistant Professor & Course Coordinator',
    facultySlug: 'rasel-hawlader',
    area: 'Springer Nature · SCOPUS & WoS Indexed · SCOPUS (Q2) Scimago (Q1) · IF (5.2)',
    date: '2026',
    publicationYear: 2026,
    link: null,
    linkLabel: null,
    publisher: 'Springer Nature',
    indexing: 'SCOPUS & WoS Indexed',
    quartile: 'SCOPUS (Q2) Scimago (Q1)',
    metrics: 'IF (5.2)',
    authorPosition: '1st',
  },
  {
    title: 'Md. Abu Issa Gazi, Md. Shahbub Alam, G. M. Anwar Hossain, SM Nahidul Islam, Muhammad Khalilur Rahman, Md. Nahiduzzaman, & Abu Ishaque Hossain (2021). Determinants of Profitability in Banking Sector: Empirical Evidence from Bangladesh. Universal Journal of Accounting and Finance, 9(6), 1377 - 1386.',
    authors: 'Md. Shahbub Alam',
    authorRole: 'Assistant Professor & Assistant Course Coordinator',
    facultySlug: 'shahbub-alam',
    area: 'Horizon Research Publishing · Scopus indexed',
    date: '2021',
    publicationYear: 2021,
    link: 'https://doi.org/10.13189/ujaf.2021.090616',
    linkLabel: null,
    publisher: 'Horizon Research Publishing',
    indexing: 'Scopus indexed',
    quartile: null,
    metrics: null,
    authorPosition: '2nd',
  },
  {
    title: 'Md. Shahbub Alam, Md. Rasel Hawlader, & Farjana Yeasmin Chowdhury (2024). Job Satisfaction of Bankers in Islami Shariah-based Private Commercial Banks of Bangladesh: Application of Job Characteristics Model. International Journal of Business, Management and Economics, 5(3), 220 - 235.',
    authors: 'Md. Shahbub Alam',
    authorRole: 'Assistant Professor & Assistant Course Coordinator',
    facultySlug: 'shahbub-alam',
    area: 'Training & Research Institute Jeramba Ilmu Sukses',
    date: '2024',
    publicationYear: 2024,
    link: 'https://doi.org/10.47747/ijbme.v5i3.1826',
    linkLabel: null,
    publisher: 'Training & Research Institute Jeramba Ilmu Sukses',
    indexing: null,
    quartile: null,
    metrics: null,
    authorPosition: '1st',
  },
  {
    title: 'G. M. Anwar Hossain, Dr. Md. Ruhul Amin, & Md. Shahbub Alam (2025). Profitability Analysis of Conventional and Islamic Banks in Bangladesh: A Comparative Page 2 of 4 Study. International Journal of Business, Management and Economics, 6(1), 1 - 20.',
    authors: 'Md. Shahbub Alam',
    authorRole: 'Assistant Professor & Assistant Course Coordinator',
    facultySlug: 'shahbub-alam',
    area: 'Bon View Publishing',
    date: '2025',
    publicationYear: 2025,
    link: 'https://doi.org/10.47747/ijbme.v6i1.2454',
    linkLabel: null,
    publisher: 'Bon View Publishing',
    indexing: null,
    quartile: null,
    metrics: null,
    authorPosition: '3rd',
  },
  {
    title: 'Mohammad Rashed Hasan Polas, Md. Shahbub Alam, Mohammad Falahat, Md. Tajbir Husain, Md. Omar Faruque Molla (2025). To the Moon and Beyond: How Nano Entrepreneurs and Digital Currency Are Revolutionizing the Future of Business in Space!. In M. Arslan & A. Faizulayev (Eds.), FinTech and Robotics Advancements for Green Finance and Investment (pp. 65-102). IGI Global Scientific Publishing. 3373-0355-0.ch003',
    authors: 'Md. Shahbub Alam',
    authorRole: 'Assistant Professor & Assistant Course Coordinator',
    facultySlug: 'shahbub-alam',
    area: 'IGI Global Scientific Publishing · Scopus indexed',
    date: '2025',
    publicationYear: 2025,
    link: 'https://doi.org/10.4018/979-8',
    linkLabel: null,
    publisher: 'IGI Global Scientific Publishing',
    indexing: 'Scopus indexed',
    quartile: null,
    metrics: null,
    authorPosition: '2nd',
  },
  {
    title: 'Ashik Das, Md. Shahbub Alam, Md. Rasel Hawlader (2025). Unveiling the impact of green innovation on organizational performance: An empirical study on FMCG sector in Bangladesh. Annals of Management and Organization Research, 7(2), 247-267.',
    authors: 'Md. Shahbub Alam',
    authorRole: 'Assistant Professor & Assistant Course Coordinator',
    facultySlug: 'shahbub-alam',
    area: 'Goodwood Publishing',
    date: '2025',
    publicationYear: 2025,
    link: 'https://doi.org/10.35912/amor.v7i2.3241',
    linkLabel: null,
    publisher: 'Goodwood Publishing',
    indexing: null,
    quartile: null,
    metrics: null,
    authorPosition: '2nd',
  },
  {
    title: 'G. M. Anwar Hossain, Md. Ruhul Amin, Md. Shahbub Alam, & Atifa Kafi (2025). A Comparative Examination of Productivity in Islamic and Conventional Banking in Bangladesh. Journal of Comprehensive Business Administration Research, 3(1), 39–51.',
    authors: 'Md. Shahbub Alam',
    authorRole: 'Assistant Professor & Assistant Course Coordinator',
    facultySlug: 'shahbub-alam',
    area: 'Bon View Publishing',
    date: '2025',
    publicationYear: 2025,
    link: 'https://doi.org/10.47852/bonviewJCBAR52024694',
    linkLabel: null,
    publisher: 'Bon View Publishing',
    indexing: null,
    quartile: null,
    metrics: null,
    authorPosition: '3rd',
  },
  {
    title: 'Hawlader, M. R., Polas, M. R. H., Das, A., Alam, M. S., Uddin, S. M., Hasan, T., & Pantho, O. G. (2026). Green human resource management and green innovation as drivers of environmental performance in readymade garment firms. Discover Sustainability (2026).',
    authors: 'Md. Shahbub Alam',
    authorRole: 'Assistant Professor & Assistant Course Coordinator',
    facultySlug: 'shahbub-alam',
    area: 'Springer Nature · SCOPUS & WoS Indexed · SCOPUS (Q2) Scimago (Q1) · IF (5.2)',
    date: '2026',
    publicationYear: 2026,
    link: null,
    linkLabel: null,
    publisher: 'Springer Nature',
    indexing: 'SCOPUS & WoS Indexed',
    quartile: 'SCOPUS (Q2) Scimago (Q1)',
    metrics: 'IF (5.2)',
    authorPosition: '4th',
  },
  {
    title: 'Rashed, M., Hossain, M. I., Akter, T., Ali, M. A., Rabbi, M. F., & Mamun, M. A. A. (2026). Sustainable Green Practices in Manufacturing Organizations: A hybrid methods from a Green Dynamic Capability Aspects. Journal of Innovation & Knowledge',
    authors: 'Md. Ashraf Ali',
    authorRole: 'Assistant Professor',
    facultySlug: 'ashraf-ali',
    area: 'Elsevier · (Scopus- WoS-SSCI, ABDC-A). · Q1 · Cite Score 24.7 Impact Factor 14.0',
    date: '2026',
    publicationYear: 2026,
    link: 'https://doi.org/10.1016/j.jik.2026.101015',
    linkLabel: null,
    publisher: 'Elsevier',
    indexing: '(Scopus- WoS-SSCI, ABDC-A).',
    quartile: 'Q1',
    metrics: 'Cite Score 24.7 Impact Factor 14.0',
    authorPosition: '4th',
  },
  {
    title: 'MM Alom, MA Hossain, N Hafiz, MA Ali, R Mostafa.,(2026). Academic Research in Universities of an Emerging Country: Trends and Future Directions for Higher Education. International Research Journal of Multidisciplinary Scope (IRJMS), 2026; 7(1): 338-356 DOI: 10.47857/irjms.2026.v07i01.07054',
    authors: 'Md. Ashraf Ali',
    authorRole: 'Assistant Professor',
    facultySlug: 'ashraf-ali',
    area: 'Scopus SCImago · Q4 · Cite Score 0.6',
    date: '2026',
    publicationYear: 2026,
    link: null,
    linkLabel: null,
    publisher: null,
    indexing: 'Scopus SCImago',
    quartile: 'Q4',
    metrics: 'Cite Score 0.6',
    authorPosition: '4th',
  },
  {
    title: 'Muhammad, M., Mamun. M. A. A., Ali, M. A., Hossain, M. M., Tarin, N. K., Hossain, B., Mostafa, R., & Ahmed, H. (2025). Exploring the mediating role of appraisal fairness between the relationship of ethical behaviour and employee performance: moderating role of organizational culture. Discover Sustainability (Scopus Q1,). DOI: 10.1007/s43621-025-02060-5.',
    authors: 'Md. Ashraf Ali',
    authorRole: 'Assistant Professor',
    facultySlug: 'ashraf-ali',
    area: 'Springer Nature · Scopus · Q1 · Cite Score 2.6. Impact Factor 5.2 (2025)',
    date: '2025',
    publicationYear: 2025,
    link: null,
    linkLabel: null,
    publisher: 'Springer Nature',
    indexing: 'Scopus',
    quartile: 'Q1',
    metrics: 'Cite Score 2.6. Impact Factor 5.2 (2025)',
    authorPosition: '3rd',
  },
  {
    title: 'Alom, K., Rahman, M. Z., Khan, A. I., Akbar, D., Hossain, M. M., Ali, M. A., & Mallick, A. (2025). Digital finance leads women entrepreneurship and poverty mitigation for sustainable development in Bangladesh. Journal of Innovation and Entrepreneurship.',
    authors: 'Md. Ashraf Ali',
    authorRole: 'Assistant Professor',
    facultySlug: 'ashraf-ali',
    area: 'Springer Nature · SCOPUS · Q1 · Cite score 7.2, Impact Factor 2.068',
    date: '2023',
    publicationYear: 2023,
    link: 'https://doi.org/10.1186/s13731-025-00471-2',
    linkLabel: null,
    publisher: 'Springer Nature',
    indexing: 'SCOPUS',
    quartile: 'Q1',
    metrics: 'Cite score 7.2, Impact Factor 2.068',
    authorPosition: '6th',
  },
  {
    title: 'Biswas, M. R., & Rabbi, M. F. (2024). Annotated Bangla natural language processing (BNLP) using Python and machine learning. Asian Journal of Language, Literature and Culture Studies, 7(3), 573-588.',
    authors: 'Md. Fajle Rabbi',
    authorRole: 'Lecturer & Assistant Course Coordinator',
    facultySlug: 'fajle-rabbi',
    area: 'Ms. M. B. Mondal, Ph.D.',
    date: '2024',
    publicationYear: 2024,
    link: 'https://doi.org/10.9734/ajl2c/2024/v7i3206',
    linkLabel: null,
    publisher: 'Ms. M. B. Mondal, Ph.D.',
    indexing: null,
    quartile: null,
    metrics: null,
    authorPosition: '2nd',
  },
  {
    title: 'M. N. Howlader, B. Paul, S. A. Z. Alif, M. F. Rabbi, and A. Islam, "Integrative ML and DL Strategies for Renewable Energy Forecasting: Performance and Feature Attribution in Solar and Wind Datasets," in Proceedings of the 4th IEEE International Conference on Power, Electrical, Electronics & Industrial Applications (PEEIACON 2025), Dhaka, Bangladesh, Dec. 4–5, 2025.',
    authors: 'Md. Fajle Rabbi',
    authorRole: 'Lecturer & Assistant Course Coordinator',
    facultySlug: 'fajle-rabbi',
    area: 'IEEE Xplore',
    date: '2025',
    publicationYear: 2025,
    link: null,
    linkLabel: null,
    publisher: 'IEEE Xplore',
    indexing: null,
    quartile: null,
    metrics: null,
    authorPosition: '4th',
  },
  {
    title: 'Rashed, M., Hossain, M. I., Akter, T., Ali, M. A., Rabbi, M. F., & Al Mamun, M. A. (2026). Sustainable green practices and knowledge in manufacturing organisations: Hybrid methods from a green dynamic capability approach. Journal of Innovation & Knowledge, 16, 101015.',
    authors: 'Md. Fajle Rabbi',
    authorRole: 'Lecturer & Assistant Course Coordinator',
    facultySlug: 'fajle-rabbi',
    area: 'Elsevier B.V. · Scopus, Wos & ABDC · Q1 · Cite Score: 24.7',
    date: '2026',
    publicationYear: 2026,
    link: 'https://doi.org/10.1016/j.jik.2026.101015',
    linkLabel: null,
    publisher: 'Elsevier B.V.',
    indexing: 'Scopus, Wos & ABDC',
    quartile: 'Q1',
    metrics: 'Cite Score: 24.7',
    authorPosition: '5th',
  },
  {
    title: 'Howlader, M. N., Chowdhury, S., Al Imon, K. A., Khan, G. J., Mehedi, M. K. H., Rabbi, M. F., ... & Al Zami Alif, S. (2026). Design and implementation of a low-cost IoT-enabled dual-axis photovoltaic tracking system with experimental and simulation-based validation. Journal of Electrical Systems and Information Technology, 13(1), 44.',
    authors: 'Md. Fajle Rabbi',
    authorRole: 'Lecturer & Assistant Course Coordinator',
    facultySlug: 'fajle-rabbi',
    area: 'Springer Nature · Scopus & Wos · Q2 · Cite Score: 2.5',
    date: '2026',
    publicationYear: 2026,
    link: 'https://doi.org/10.1186/s43067-026-00351-z',
    linkLabel: null,
    publisher: 'Springer Nature',
    indexing: 'Scopus & Wos',
    quartile: 'Q2',
    metrics: 'Cite Score: 2.5',
    authorPosition: '6th',
  },
  {
    title: 'Sharmin, S., Rahman, M. H. A., & Karim, D. N. (2022). Green Human Resource Management Practices and Organizational Citizenship Behaviour towards the Environment in the Banking Sector in Bangladesh. Bangladesh Journal of Public Administration, 30(1), 29-48.',
    authors: 'Shahnaz Sharmin',
    authorRole: 'Lecturer & Exam Coordinator',
    facultySlug: 'shahnaz-sharmin',
    area: 'Bangladesh Public Administration Training Centre (BPATC) · Non-Indexed',
    date: '2022',
    publicationYear: 2022,
    link: 'https://doi.org/10.36609/bjpa.v30i1.111',
    linkLabel: null,
    publisher: 'Bangladesh Public Administration Training Centre (BPATC)',
    indexing: 'Non-Indexed',
    quartile: null,
    metrics: null,
    authorPosition: '1st',
  },
  {
    title: 'Akter, S. K., Fatema, K., Akter, F., Nitu, N. R. S., Das, M. K., & Sharmin, S. (2025). Technological Advancement as a Catalyst for Women Empowerment through Entrepreneurship: Post Covid-19 Scenario in Bangladesh. Journal of Information Systems Engineering and Management, 10(40), 10–17.',
    authors: 'Shahnaz Sharmin',
    authorRole: 'Lecturer & Exam Coordinator',
    facultySlug: 'shahnaz-sharmin',
    area: 'International Association for Digital Transformation and Technological Innovation · Scopus · Q3 · 1.31',
    date: '2025',
    publicationYear: 2025,
    link: 'https://doi.org/10.52783/jisem.v10i40s.7242',
    linkLabel: null,
    publisher: 'International Association for Digital Transformation and Technological Innovation',
    indexing: 'Scopus',
    quartile: 'Q3',
    metrics: '1.31',
    authorPosition: '6th',
  },
  {
    title: 'Muhammad, M., Al Mamun, M. A., Ali, M. A., Hossain, M. M., Tarin, N. K., Hossain, B., ... & Ahmed, H. (2025). Exploring the mediating role of appraisal fairness between the relationship of ethical behaviour and employee performance: moderating role of organisational culture. Discover Sustainability, 6(1), 1-25.',
    authors: 'Naima Khan Tarin',
    authorRole: 'Lecturer',
    facultySlug: 'naima-khan-tarin',
    area: 'Springer Nature · Scoupus & WoS · SCOPUS (Q2) Scimago (Q1) · IF (5.2)',
    date: '2025',
    publicationYear: 2025,
    link: 'https://doi.org/10.1007/s43621-025-02060-5',
    linkLabel: null,
    publisher: 'Springer Nature',
    indexing: 'Scoupus & WoS',
    quartile: 'SCOPUS (Q2) Scimago (Q1)',
    metrics: 'IF (5.2)',
    authorPosition: '5th',
  },
  {
    title: 'Himel, T.H., Khan, S.I., Sharmin, S., Tarin, N.K. (2026). Understanding the Drivers of Green Entrepreneurial Intentions: An Application of Shapero’s Entrepreneurial Event Model. In: Duarte Correia, S., Lahby, M. (eds) Green Technologies and Sustainable Intelligence—Volume I: Theoretical Aspects and Computational Approaches. ISGTA 2025. Springer Proceedings in Physics, vol 350. Springer, Cham. (Conference paper)',
    authors: 'Naima Khan Tarin',
    authorRole: 'Lecturer',
    facultySlug: 'naima-khan-tarin',
    area: 'Springer Nature',
    date: '2026',
    publicationYear: 2026,
    link: 'https://doi.org/10.1007/978-3-032-19038-3_12',
    linkLabel: null,
    publisher: 'Springer Nature',
    indexing: null,
    quartile: null,
    metrics: null,
    authorPosition: '4th',
  },
];
